version: "3.8"

services:
  api:
    build: .
    volumes:
      - .:/code
    depends_on:
      - redis
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    volumes:
      - .:/code
    depends_on:
      - redis
    command: arq app.workers.WorkerSettings

  redis:
    image: redis:7
    ports:
      - "6379:6379"
